### ISSUE TITLE
In intro_to_python, use urllib.parse.urljoin for creation of URL strings

### ISSUE THREAD

**Issue by dannguyen** [sul-cidr/python_workshops#4]
Under "Another text scraping example", the `create_url` function:

```py
# Since the href didn't give us a full url, we use a function to build one
def create_url(url):
    return 'https://python.swaroopch.com/' + url
```

Might be worth introducing best practices (and conveniences) to include a refactored example in which the `urllib.parse.urljoin` library is used, as it would make `create_url` more robust in any URL collecting scenario:

https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin

```py
# Having create_url wrap around the builtin `urllib.parse.urljoin` method
from urllib.parse import urljoin
def create_url(url):
    return urljoin('https://python.swaroopch.com', url)
```

I think it's worth including the original implementation, so that people know that what's going on is basically string concatenation. But that even that is too mundane -- and error-prone of a task to do without using a builtin library.

**Comment by versae** [comment]
Thanks for the tip @dannguyen! We thought about using `urllib.parse.urljoin()`, but the fact that it handles the concept of base URI, path and fragment, and that it might not be intuitive for first timers, made us choose not to put it in the workshop.

The example below illustrates the kind of confusion we are trying to avoid.
```python
>>> urljoin('http://some/more', 'thing')
'http://some/thing'

>>> urljoin('http://some/more/', 'thing')
'http://some/more/thing'
```

But we agree in that following best practices is always something to foster and look for, especially when teaching to those new to the language.
